### PR TITLE
RHEL builds of dynamic module for EL 6, 7, 8

### PR DESCRIPTION
**Pull request by dvershinin**
Information about RPM packages for EL 6, 7, 8. 
Some formatting issues addressed.

### CODE REVIEW

**Comment by dvershinin** [comment]
@winshining thanks for noticing the bug with the description :)

I have included the sample files and made another release.

My guess about the RHEL 6.x issue is that you were on a 32 bit OS, for which there was no build.
Now it should work. Try: 

    yum clean all && yum install nginx-module-flv

The automatic build system makes releases for EL 6/7 64 bit only for now.
Here's a bit on how it works:

* When you will mark a release for (yet another) version [here](https://github.com/winshining/nginx-http-flv-module/releases), the watcher script for the new release will notice it within 24 hrs
* Then it will kick off / start the build of RPMs and push them to the repo. 

The rest (EL6 i686 + EL8 64 bit). I've built and added manually. 

For installing in EL8, there is one important gotcha that I forgot and added now, in regards with passing switch `--disablerepo=rhel-8-for-x86_64-appstream-rpms`. This is required because that repository has an NGINX stream version 1.14. Even it's older, `dnf` still has preference for installing packages from stream repository. So disabling it is the workaround I found working.

**Comment by winshining** [comment]
I found the reason, it had nothing to do with arch (I tested on x86_64 arch) but SSL.
The version was too old to access the website, so at last I downloaded nginx and nginx-http-flv-module manually and it worked fine.
Thanks again!

**Comment by winshining** [comment]
@dvershinin Hello, I got an error just now as follow:
[root@localhost]# yum install nginx-module-flv
已加载插件：fastestmirror, langpacks
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
getpagespeed-extras                                                                                                  |  27 kB  00:00:00     
https://extras.getpagespeed.com/redhat/7/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for getpagespeed-extras: Damaged repomd.xml file
正在尝试其它镜像。


 One of the configured repositories failed (GetPageSpeed packages for Enterprise Linux 7 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=getpagespeed-extras ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable getpagespeed-extras
        or
            subscription-manager repos --disable=getpagespeed-extras

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=getpagespeed-extras.skip_if_unavailable=true

failure: repodata/repomd.xml from getpagespeed-extras: [Errno 256] No more mirrors to try.
https://extras.getpagespeed.com/redhat/7/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for getpagespeed-extras: Damaged repomd.xml file

There seems to be something wrong with software source.

**Comment by dvershinin** [comment]
@winshining it's not that it's broken, but it has been paywalled.
Too many modules (30+) to support and I had 0 donations in years.
The RHEL/CentOS 8 is still free, e.g. this is freely installable [here](https://extras.getpagespeed.com/redhat/8/x86_64/repoview/nginx-module-flv.html).

**Pull request merged**
